spring:
  application:
    name: 54_Spring_Security_JDBC_AuthApp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: manish123
    url: jdbc:mysql://localhost:3306/jrtp
    username: root
  jpa:
    show-sql: true