pipeline {
  agent any

  tools {
    jdk   'JDK17'
    maven 'Maven_3_9'
  }

  options {
    timestamps()
    ansiColor('xterm')
    buildDiscarder(logRotator(numToKeepStr: '30'))
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build & Unit Tests') {
      steps {
        bat 'mvn -B clean package'
      }
      post {
        always {
          junit 'target\\surefire-reports\\*.xml'
        }
      }
    }

    stage('Archive Jar') {
      steps {
        archiveArtifacts artifacts: 'target\\*.jar', fingerprint: true
      }
    }
  }

  post {
    success {
      echo "✔ Build #${env.BUILD_NUMBER} OK for ${env.JOB_NAME}"
    }
    failure {
      echo "✘ Build failed — console output check karo."
    }
  }
}
