spring:
  application:
    name: greet-api
  boot:
    admin:
      client:
        url: http://localhost:1111/



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
