spring:
  application:
    name: Batch
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: AshokIT@123
    url: jdbc:mysql://localhost:3306/spring_Batch
    username: ashokit
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
   jdbc:
      initialize-schema: always